In [1]:
pwd

'C:\\Users\\Henry\\Desktop\\my Portfolio\\Deep_learning_classification'

In [27]:
import numpy as np
from numpy.random import seed 
seed(1) 
import pandas as pd
import tensorflow as tf
!pip install keras
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
tf.random.set_seed(1234)
from keras.utils import to_categorical
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt


In [3]:
data = pd.read_csv('data_modeling.csv')
data.head(2)

sepal_width  petal_width  species
0    -0.587764     0.001753        1
1     1.726266    -1.181504        0

In [4]:
data.columns = ['']*len(data.columns)
data.index = ['']*len(data.index)
data

-0.587764  0.001753  1
    1.726266 -1.181504  0
   -1.050569  1.447956  2
   -0.356361  0.396172  1
   -0.587764  0.264699  1
..       ...       ... ..
   -0.587764  0.133226  1
   -1.281972  0.659118  2
    2.189072 -1.312977  0
   -1.050569  0.001753  1
   -0.124958  1.185010  2

[150 rows x 3 columns]

In [5]:
data_1=data.iloc[:,-1]

In [6]:
data_2 =data.iloc[:,:-1]

In [7]:
y_cat = to_categorical(data_1)

In [8]:
y_cat[:3]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [9]:
y_cat.shape

(150, 3)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_2, y_cat , test_size=0.3, random_state=7)

In [11]:
# MODELING FOR 8 FEATURES
# build the model using Keras approach

input_size = 2   # number of features
output_size =3    
hidden_layer_size =100  
Early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

In [12]:
from keras.models import Sequential
# Import `Dense` from `keras.layers`
from keras.layers import Dense
# Initialize the constructor
model = Sequential()
# Add an input layer 
model.add(Dense(12, activation='relu', input_shape=(2,)))
# Add one hidden layer 
model.add(Dense(8, activation='relu'))
# Add an output layer 
model.add(Dense(3, activation='softmax'))

In [13]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
                   
model.fit(X_train, y_train,epochs=20, batch_size=9,callbacks=[Early_stopping],validation_split=0.1, verbose=2)

Epoch 1/20
11/11 - 1s - loss: 1.0765 - accuracy: 0.4043 - val_loss: 1.0252 - val_accuracy: 0.5455
Epoch 2/20
11/11 - 0s - loss: 1.0303 - accuracy: 0.4468 - val_loss: 0.9984 - val_accuracy: 0.5455
Epoch 3/20
11/11 - 0s - loss: 0.9920 - accuracy: 0.4574 - val_loss: 0.9765 - val_accuracy: 0.5455
Epoch 4/20
11/11 - 0s - loss: 0.9570 - accuracy: 0.4574 - val_loss: 0.9537 - val_accuracy: 0.5455
Epoch 5/20
11/11 - 0s - loss: 0.9266 - accuracy: 0.4574 - val_loss: 0.9239 - val_accuracy: 0.5455
Epoch 6/20
11/11 - 0s - loss: 0.8974 - accuracy: 0.4574 - val_loss: 0.8909 - val_accuracy: 0.5455
Epoch 7/20
11/11 - 0s - loss: 0.8706 - accuracy: 0.5000 - val_loss: 0.8614 - val_accuracy: 0.5455
Epoch 8/20
11/11 - 0s - loss: 0.8443 - accuracy: 0.5106 - val_loss: 0.8340 - val_accuracy: 0.5455
Epoch 9/20
11/11 - 0s - loss: 0.8207 - accuracy: 0.5106 - val_loss: 0.8056 - val_accuracy: 0.6364
Epoch 10/20
11/11 - 0s - loss: 0.7984 - accuracy: 0.5106 - val_loss: 0.7821 - val_accuracy: 0.6364
Epoch 11/20
11/11 -

In [14]:
score = model.evaluate(X_train,y_train,verbose=1)
print(score)

4/4 [==============================] - 0s 997us/step - loss: 0.5868 - accuracy: 0.8571
[0.5868431925773621, 0.8571428656578064]


In [15]:
y_pred = model.predict( X_test)
y_pred

array([[0.04323119, 0.0753535 , 0.88141537],
       [0.11190282, 0.22834888, 0.6597483 ],
       [0.06272735, 0.17547496, 0.76179767],
       [0.2358574 , 0.49264446, 0.2714981 ],
       [0.04323119, 0.0753535 , 0.88141537],
       [0.17551208, 0.18595931, 0.6385286 ],
       [0.15678106, 0.34616023, 0.4970587 ],
       [0.02467579, 0.03975132, 0.93557286],
       [0.4299506 , 0.21103458, 0.35901484],
       [0.04323119, 0.0753535 , 0.88141537],
       [0.09380066, 0.7094852 , 0.19671409],
       [0.4434213 , 0.18210042, 0.37447822],
       [0.19313323, 0.37824172, 0.42862502],
       [0.17302534, 0.4407509 , 0.38622382],
       [0.4105416 , 0.24305594, 0.34640244],
       [0.04369636, 0.1559351 , 0.8003685 ],
       [0.44521356, 0.17105305, 0.38373333],
       [0.08653519, 0.19360335, 0.71986145],
       [0.14012277, 0.3985134 , 0.46136376],
       [0.45116895, 0.13091826, 0.41791278],
       [0.44521356, 0.17105305, 0.38373333],
       [0.18361238, 0.4122193 , 0.40416837],
       [0.

In [16]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1) 

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test_class, y_pred_class )
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 86.67%


In [18]:
print(classification_report(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.68      0.81        19
           2       0.67      1.00      0.80        12

    accuracy                           0.87        45
   macro avg       0.89      0.89      0.87        45
weighted avg       0.91      0.87      0.87        45



In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test_class,y_pred_class)

array([[14,  0,  0],
       [ 0, 13,  6],
       [ 0,  0, 12]], dtype=int64)